# Generated by Django 5.2 on 2026-01-06 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='podcasts/')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='episodes/')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.podcast')),
            ],
        ),
    ]
