# Generated by Django 5.2 on 2026-01-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='episode_id',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='podcast_id',
        ),
        migrations.AlterField(
            model_name='episode',
            name='audio',
            field=models.FileField(upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
