# Generated by Django 5.2 on 2026-01-06 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_remove_episode_episode_id_remove_podcast_podcast_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='podcast.podcast'),
        ),
    ]
