# Generated by Django 5.2 on 2026-01-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.URLField(),
        ),
    ]
